### ISSUE TITLE
Favourite Tab for Hacks, Bypass, Etc.

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#168]
it would be really cool to have a new tab where we can put hacks and such as favourite, so we don't have to search for them again every time if we don't have a shortcut (maybe because we basically smash keyboards when we die at n%>60, which would activate things without us knowing). also make it possible to sort either by alphabetical order or manually, to like set the ones we always use on top/bottom and the ones we don't really use that much but still useful on the other side

seems to be already included in v7 tho so this isn't necessary anymore

**Comment by Brittank88** [comment]
Next time, please try not to combine issues! Makes it easier if we can track those two things (favourites and tab layout saving) separately.

**Comment by zohnannor** [comment]
I think the issue is resolved since this option is available in v7, but I would also suggest a better interaction for adding favorites to the list. I think finding hacks in drop-down lists is not a very good way of selecting them. It would be better if users could add hacks to the list by clicking them in the main windows, like, ctrl+clicking or just using right mouse button. And to be honest, MHv6's way of setting the keybinds was better in my oppinion. Any way, thank you Absolute for your work!

**Comment by absoIute** [comment]
Yep, added in v7, will look into redoing the selection system
