### ISSUE TITLE
RGB icons issue

### ISSUE THREAD

**Issue by mikolps** [absoIute/Mega-Hack-Pro-Future#23]
so when i put the RGB icon thing to the max (spamming 9) there is way too high text limit first of all. and when i put max 9's my icons just goes completely black.

**Comment by Brittank88** [comment]
I appreciate that there's a certain threshold past which the value you put in doesn't really matter anymore, however, if it doesn't do anything harmful is there any reason to actually impose a limit?

People can ultimately just... Not set a value that high. Its better to only impose limits that prevent damage, rather than restrict things "just because it should".

Thats my view of it anyways.

**Comment by absoIute** [comment]
same, I am also too lazy to implement a cap
