### ISSUE TITLE
Unrandomizer & X Pos Limit Bypasser

### ISSUE THREAD

**Issue by succmydecc** [absoIute/Mega-Hack-Pro-Future#357]
Unrandomizer for GD, exists in v5 but doesn't exist in v6 and upper and allow for the xpos limit to be bypassed. To prove that it is possible (just in case if you dont) here is a program trollin (tpll member) made: https://github.com/succmydecc/xposlimitbypasserarchive. Its buggy, the original creator isn't proud of it and deleted it (link is a archive of the program) and its the only thing we have so maybe someone like you absolllute can improve this and make it a internal menu.

**Comment by absoIute** [comment]
May add the unrandomiser back at some point but probably not an X pos bypass for the editor, since going that high just kills the player anyway

**Comment by succmydecc** [comment]
No, not for the editor for the actual game and I mean not the y pos the x pos

**Comment by absoIute** [comment]
What do you mean then, so you can go to a higher y-pos without getting killed in-game?

**Comment by succmydecc** [comment]
Do you not understand me? Do you know what the x pos limit is?

**Comment by absoIute** [comment]
Not possible, it's just how floats work. Basically your X Position can only have a certain amount of precision, so once it's a larger number (lets say say 10^10) the least significant digits aren't accounted for, so adding a small amount to the number does nothing and it stays the same, which is why the cube stops moving.

A proper fix would need to be implemented by Rob

**Comment by succmydecc** [comment]
https://github.com/succmydecc/xposlimitbypasserarchive/releases/tag/archived how is it not possible??? this is a exe that allows you go farther in timeless???

**Comment by succmydecc** [comment]
sorry to break it to you, but if a dev that doesn't get paid and has little coding knowledge can code a xpos when you cant, is kinda sad.

**Comment by succmydecc** [comment]
https://github.com/succmydecc/xposlimitbypasserarchive/releases/tag/archived how is it not possible??? this is a exe that allows you go farther in timeless and xpos limit??? @absoIute

**Comment by Brittank88** [comment]
Without the source code, linking this doesn't do too much. From what I was able to gather, it clears VirusTotal and was written in Python 3.9. I don't want to risk opening it still, I kinda don't trust it. It's 28 MB, which is massively bloated if it's making a single modification to the game.

**Comment by zohnannor** [comment]
If it's written in Python, it's clear why it's 28 megs because there is literally Python Virtual Machine included in that executable.

<details>
<summary>Spoiler: some StackOverflow links regarding executable size</summary>

[Reducing size of pyinstaller exe](https://stackoverflow.com/questions/47692213/reducing-size-of-pyinstaller-exe)
[size of executable using pyinstaller and numpy](https://stackoverflow.com/questions/47769904/size-of-executable-using-pyinstaller-and-numpy)
</details>

I wouldn't risk runing that program too tho 😅

**Comment by succmydecc** [comment]
> Without the source code, linking this doesn't do too much. From what I was able to gather, it clears VirusTotal and was written in Python 3.9. I don't want to risk opening it still, I kinda don't trust it. It's 28 MB, which is massively bloated if it's making a single modification to the game.

I get why you don't trust me but, the source code (or the original creator) was open for anyone, so you can debug it with IDA pro

**Comment by succmydecc** [comment]
![Capture](https://user-images.githubusercontent.com/82858330/150917465-7face1ba-4dc9-4353-97a8-4dc7f6937122.PNG)
heres proof if your wondering

**Comment by zohnannor** [comment]
bro what you have to be trolling or smth

**Comment by absoIute** [comment]
I'm not opening that lol

**Comment by Nicko2102** [comment]
trying to IP grab absolute lmao

**Comment by succmydecc** [comment]
@absoIute bruh, you can trust me

**Comment by succmydecc** [comment]
also cant you just decompile it?
