### ISSUE TITLE
MHv7 Discord Server(?)

### ISSUE THREAD

**Issue by MainConMan** [absoIute/Mega-Hack-Pro-Future#438]
It would be cool if Absolute (or maybe Brittank) made a discord server, but I completely understand if you don't want to do this.

**Comment by Nicko2102** [comment]
Good idea! might be a lot of work though? and it could render this tracker obsolete in a way

**Comment by MainConMan** [comment]
> Good idea! might be a lot of work though, and it could render this tracker obsolete in a way

Yeah, this is true, there are definitely pros and cons to it, but the server could also be useful too.

**Comment by absoIute** [comment]
Something I've just wanted to avoid I'm afraid, managing 3 support channels is already a lot of work & I don't want to add to that

**Comment by Nicko2102** [comment]
fair enough

**Comment by Brittank88** [comment]
> and it could render this tracker obsolete in a way

I understand the enthusiasm but trust me a purpose-built tracker will always perform better than a messaging program's features basically retrofitted to serve a similar function.

**Comment by Brittank88** [comment]
I'd love a Discord server but yeah it's a lot of work to maintain.

**Comment by MainConMan** [comment]
I understand completely, it would be a lot of work, especially with everything else Absolute is doing. I'd probably make the same decision if I were in his shoes.

**Comment by Nicko2102** [comment]
> > and it could render this tracker obsolete in a way
> 
> I understand the enthusiasm but trust me a purpose-built tracker will always perform better than a messaging program's features basically retrofitted to serve a similar function.

Oh yeah i know, i meant that as a downside to having a server lol, this would 100% work better

**Comment by NewAlexGamer** [comment]
i'm proposing this again because i've recently seen you can make posts now in discord inside a channel, add labels to it, etc..., and i was thinking that would be basically the same as this repository but without the needing of waiting for collaborators to add labels and stuff, no need for an email that people check once in a while if not once every few days. instead if you ping someone on discord they basically reply as soon as they notice that, if they're online of course

what can be done is permanently moving from this github repository to a discord server. no need to manage that yourself, you can get moderators and stuff. this way people are more familiar with searching already submitted problems/features. most of them don't know how to even navigate in a github repository (take me a year ago). instead when people come here or on twitter and ask "why is it not working", instead of an issue here for a simple "it tells me i don't have the right directory" or "i accidentally turned speedhack at 0.000000000001 with classic mode on help", there would just be a channel made for that with mods that can help and answer that
